#PV is set up by ops
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: telemetry-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/telemetry-mysql
