apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  #namespace: telemetry
spec:
  selector:
    #using this matchLabel value to attach to service (service-deployment connector)
    matchLabels:
      app: app
  # Set instances of app    
  replicas: 2
  strategy:
    type: RollingUpdate
  #this is basically the pod template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: "telemetry-app"
        image: "labuser/telemetry:latest"
        ports:
        - containerPort: 8080
        #Set env variables in K8s directly - No need to define in Dockerfile
        env:
        - name: DB_HOST
          #this value points to the name of mysql-service.
          #these values are typically read from a secret config.
          #value: mysql-service
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: service.database
        - name: DB_PORT
          #value: '3306'
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: service.database.port
        - name: DB_NAME
          #value: "telemetrydb"
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: service.database.name
        - name: DB_USER
          #value: "root"
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: service.database.user
        - name: DB_PASSWORD
          #value: "password"
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: service.database.password
          #ensure that local image is pulled first
        imagePullPolicy: IfNotPresent
